### ISSUE TITLE
Sends JSON when Stripe expects application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by jordanmhiller** [alnewkirk/API-Stripe#1]
When making POST requests the module seems to be sending JSON, but Stripe requires application/x-www-form-urlencoded:

Example:
    my $stripe = API::Stripe->new(
        username	=> STRIPE_SECRET_KEY,
        identifier	=> 'APPLICATION NAME',
    );
    
    $stripe->debug(1);
    $stripe->fatal(1);

	my $customer = $stripe->customers->create( data => {
		source		=> 'tok_***',
	} );

Output is:

POST /v1/customers HTTP/1.1
User-Agent: APPLICATION NAME
Content-Type: application/json
Accept-Encoding: gzip
Content-Length: 41
Authorization: Basic ***
Host: api.stripe.com

{"source":"tok_***"}

HTTP/1.1 400 Bad Request
Access-Control-Allow-Credentials: true
Connection: keep-alive
Cache-Control: no-cache, no-store
Access-Control-Allow-Origin: *
Date: Fri, 28 Aug 2015 20:17:23 GMT
Stripe-Version: 2015-08-19
Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS, DELETE
Content-Length: 236
Access-Control-Max-Age: 300
Content-Type: application/json
Server: nginx
Request-Id: req_***

{
  "error": {
    "type": "invalid_request_error",
    "message": "Invalid request (check that your POST content type is application/x-www-form-urlencoded). If you have any questions, we can help at https://support.stripe.com/."
  }
}

**Comment by alnewkirk** [comment]
Sorry for the delayed response. Thanks for trying this library. This issue has been addressed in the latest release.
